-- Recreate public vw_ia* views in euro_dash, reading euro_dash.mv_resumo_assessor.
-- public views stay untouched.

CREATE OR REPLACE VIEW euro_dash.vw_ia_performa_atual AS
SELECT DISTINCT ON (cod_assessor)
  cod_assessor,
  nome_assessor,
  email,
  foto_url,
  lider,
  chave_data_assessor,
  data_posicao,
  "time",
  cluster,
  custodia_net,
  total_clientes,
  total_fp_300k,
  meta_fp300k,
  receita_b3,
  asset_m_1,
  receitas_estruturadas,
  receita_cetipados,
  receitas_ofertas_fundos,
  receitas_ofertas_rf,
  receita_renda_fixa,
  receita_seguros,
  receita_previdencia,
  receita_consorcios,
  receita_cambio,
  receita_compromissadas,
  receitas_offshore,
  captacao_entradas,
  captacao_saidas,
  captacao_liquida,
  captacao_entrada_transf,
  captacao_saida_transf,
  captacao_transf_liquida,
  captacao_liquida_total,
  captacao_liquida_total_pf,
  captacao_liquida_total_pj,
  faturamento_pj1,
  faturamento_pj2,
  meta_captacao,
  meta_ativacao_300k,
  status_assessor,
  pontos_captacao,
  pontos_roa_invest,
  pontos_roa_cs,
  ativacao_300k,
  ativacao_1kk,
  pontos_ativacoes,
  pontos_lider,
  pontos_lider_roa,
  pontos_lider_cap,
  pontos_total,
  pontos_totais_acumulado,
  repasse_total,
  receita_total,
  meta_receita,
  roa,
  total_clientes_ruptura,
  perc_fp_meta,
  media_movel_clientes_6m,
  media_movel_rupturas_6m,
  elegibilidade
FROM euro_dash.mv_resumo_assessor
WHERE nome_assessor IS NOT NULL
  AND date_trunc('month'::text, data_posicao::timestamp with time zone) = (
    SELECT date_trunc('month'::text, max(mv.data_posicao)::timestamp with time zone)
    FROM euro_dash.mv_resumo_assessor mv
  );

CREATE OR REPLACE VIEW euro_dash.vw_ia_performa_mensal AS
SELECT DISTINCT ON (cod_assessor, (date_trunc('month'::text, data_posicao::timestamp with time zone)))
  cod_assessor,
  nome_assessor,
  chave_data_assessor,
  data_posicao,
  "time",
  cluster,
  custodia_net,
  total_clientes,
  total_fp_300k,
  meta_fp300k,
  receita_b3,
  asset_m_1,
  receitas_estruturadas,
  receita_cetipados,
  receitas_ofertas_fundos,
  receitas_ofertas_rf,
  receita_renda_fixa,
  receita_seguros,
  receita_previdencia,
  receita_consorcios,
  receita_cambio,
  receita_compromissadas,
  receitas_offshore,
  captacao_entradas,
  captacao_saidas,
  captacao_liquida,
  captacao_entrada_transf,
  captacao_saida_transf,
  captacao_transf_liquida,
  captacao_liquida_total,
  captacao_liquida_total_pf,
  captacao_liquida_total_pj,
  faturamento_pj1,
  faturamento_pj2,
  meta_captacao,
  meta_ativacao_300k,
  status_assessor,
  pontos_captacao,
  pontos_roa_invest,
  pontos_roa_cs,
  ativacao_300k,
  ativacao_1kk,
  pontos_ativacoes,
  pontos_lider,
  pontos_lider_roa,
  pontos_lider_cap,
  pontos_total,
  pontos_totais_acumulado,
  repasse_total,
  receita_total,
  meta_receita,
  roa,
  total_clientes_ruptura,
  perc_fp_meta,
  media_movel_clientes_6m,
  media_movel_rupturas_6m,
  elegibilidade
FROM euro_dash.mv_resumo_assessor
WHERE nome_assessor IS NOT NULL
ORDER BY
  cod_assessor,
  date_trunc('month'::text, data_posicao::timestamp with time zone),
  data_posicao DESC;

GRANT ALL ON TABLE euro_dash.vw_ia_performa_atual TO anon, authenticated, service_role;
GRANT ALL ON TABLE euro_dash.vw_ia_performa_mensal TO anon, authenticated, service_role;
