// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kseespnvbkzxxgdjklbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZWVzcG52Ymt6eHhnZGprbGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4ODE3MTEsImV4cCI6MjA3NTQ1NzcxMX0.AF24smaQyICKiYQeaJykojCHMniqZJauBwEJpyUMK-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});